---
services:
  fpm:
    image: 'akeneo/fpm:php-7.2'
    user: 'docker'
    volumes:
      - 'akeneo-htdocs:/srv/pim:rw'
    working_dir: '/srv/pim'
    networks:
      - 'akeneo'
    env_file:
      - .env
    labels:
      traefik.enable: "false"
