---
services:
  httpd:
    image: 'httpd:2.4'
    depends_on:
      - 'fpm'
      - 'mysql'
      - 'node'
      - 'elasticsearch'
    volumes:
      - 'akeneo:/srv/pim:ro'
      - './config.d/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './config.d/apache2/akeneo.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'traefik'
      - 'akeneo'
    labels:
      traefik.enable: "true"
      traefik.http.routers.akeneo.rule: Host(`pim.gugugaga.de`) && PathPrefix(`/`)
      traefik.http.routers.akeneo.entrypoints: http,https
    # deploy:
    #   # resources:
    #   #   limits:
    #   #     cpus: '0.50'
    #   #     memory: 50M
    #   #   reservations:
    #   #     cpus: '0.25'
    #   #     memory: 20M
    #   labels:
    #     traefik.enable: "true"
    #     traefik.http.routers.akeneo.rule: Host(`pim.gugugaga.de`) && PathPrefix(`/`)
    #     traefik.http.routers.akeneo.entrypoints: http,https
